version: '3.8'

services:
  wsgi:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:80 --workers 3
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./assets:/app/src/assets
    depends_on:
      - db
      - redis

  asgi:
    build: .
    command: daphne core.asgi:application -b 0.0.0.0 -p 80
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:5-alpine@sha256:1a3c609295332f1ce603948142a132656c92a08149d7096e203058533c415b8c
    restart: unless-stopped

  db:
    image: postgres:16-alpine@sha256:7e3608e3f384b6db43c0261c73df3c48bd36e3e2fc3df88be81fcd721f206f9f
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    build:
      context: .
      target: runtime-nginx
    restart: unless-stopped
    ports:
      - ${PORT}:80
    volumes:
      - ./assets:/var/www/html/assets:ro
    depends_on:
      - asgi
      - wsgi
