# Generated by Django 4.2.6 on 2023-12-15 10:06

import apps.schedules.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_garage', '0001_initial'),
        ('device_and_screen_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cron', models.CharField(max_length=128, validators=[apps.schedules.models.isCronValid])),
                ('cron_is_reversed', models.BooleanField(default=False)),
                ('cron_explanation', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSlideshowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_slideshow_order', models.PositiveSmallIntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_slideshows', to='schedules.timeschedule')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow_schedules', to='device_and_screen_management.screen')),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_schedules', to='content_garage.slideshow')),
            ],
        ),
    ]
