# Generated by Django 4.2.6 on 2023-12-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('host_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ssh_private_key', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('restart_device', 'Can restart device'), ('restart_device_service', 'Can restart device service'), ('restart_all_pages_for_device', 'Can restart all pages for device')),
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('background', models.CharField(blank=True, choices=[(None, 'Ingen (arver fra forelder)'), ('empty', 'Blank bakgrunn'), ('shdownright', 'Spillhuset logo nede til høyre'), ('shdvd', 'Spillhuset DVD logo'), ('shdvddark', 'Spillhuset DVD logo men litt mørkere')], default='empty', max_length=64)),
                ('last_pulse', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='device_and_screen_management.device')),
            ],
            options={
                'ordering': ['device', 'name'],
                'permissions': (('restart_page', 'Can restart page'),),
            },
        ),
    ]
