# Generated by Django 4.2.6 on 2023-12-15 10:06

import apps.content_garage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('background', models.CharField(blank=True, choices=[(None, 'Ingen (arver fra forelder)'), ('empty', 'Blank bakgrunn'), ('shdownright', 'Spillhuset logo nede til høyre'), ('shdvd', 'Spillhuset DVD logo'), ('shdvddark', 'Spillhuset DVD logo men litt mørkere')], max_length=64, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('duration', models.IntegerField(default=10)),
                ('template', models.CharField(choices=[('text', 'Tekst'), ('image', 'Bilde i fullskjerm'), ('imagetext', 'Bilde med tekst'), ('imagebehindtext', 'Bilde bak tekst'), ('video', 'Video'), ('iframe', 'Nettside (iframe)'), ('clock', 'Klokke')], max_length=64)),
                ('template_data', models.JSONField()),
                ('background', models.CharField(blank=True, choices=[(None, 'Ingen (arver fra forelder)'), ('empty', 'Blank bakgrunn'), ('shdownright', 'Spillhuset logo nede til høyre'), ('shdvd', 'Spillhuset DVD logo'), ('shdvddark', 'Spillhuset DVD logo men litt mørkere')], max_length=64, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='content_garage.slideshow')),
            ],
            options={
                'ordering': ['slideshow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.content_garage.models.hash_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_log', to='content_garage.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_version_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset', '-created_at'],
            },
        ),
    ]
